swagger: '2.0'
info:
  title: 'Flower Delivery Stream API'
  version: 0.1.0-rc.1
paths:
  flower.delivery.Order-event:
    get:
      tags:
        - flower.delivery
      responses:
        '200':
          schema: {$ref: '#/definitions/OrderEvent'}
definitions:
  $ref:
    - ../ts/order-event.ts
